parserOptions:
  ecmaVersion: 2015
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true

extends: 'htmlacademy/es6'

rules:
  complexity: ["error", 10]
  max-depth: ["error", 2]
  max-len: ["error", { "code": 120 }]
  max-lines: ["error", 500]
  max-lines-per-function: ["error", 30]
  max-nested-callbacks: ["error", 1]
  max-params: ["error", 2]
  max-statements: ["error", 30]
